# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: eloston.ungoogled-chromium
PackageVersion: 141.0.7390.122
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
UpgradeBehavior: install
Protocols:
- http
- https
FileExtensions:
- crx
- htm
- html
- pdf
- url
Installers:
- Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/141.0.7390.122-1.1/ungoogled-chromium_141.0.7390.122-1.1_installer_x64.exe
  InstallerSha256: 17680DDA53D6777DEC39D40FD9083F6DCCC0A313CFE39F9ACC2FD85FDF2329C6
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
    Custom: --system-level
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/141.0.7390.122-1.1/ungoogled-chromium_141.0.7390.122-1.1_installer_x64.exe
  InstallerSha256: 17680DDA53D6777DEC39D40FD9083F6DCCC0A313CFE39F9ACC2FD85FDF2329C6
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ungoogled-chromium_141.0.7390.122-1.1_windows_x64\chrome.exe
    PortableCommandAlias: chrome
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/141.0.7390.122-1.1/ungoogled-chromium_141.0.7390.122-1.1_windows_x64.zip
  InstallerSha256: 5588F83F5B45064042B9B03928E2BDDDFF7D947F6A957B6185E3681331595C5B
  ArchiveBinariesDependOnPath: true
- Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/141.0.7390.122-1.1/ungoogled-chromium_141.0.7390.122-1.1_installer_x86.exe
  InstallerSha256: 39431750927898ADC5D6DFD51922F50021368B994E8C160784612D7B17B1F281
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
- Architecture: x86
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/141.0.7390.122-1.1/ungoogled-chromium_141.0.7390.122-1.1_installer_x86.exe
  InstallerSha256: 39431750927898ADC5D6DFD51922F50021368B994E8C160784612D7B17B1F281
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
    Custom: --system-level
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ungoogled-chromium_141.0.7390.122-1.1_windows_x86\chrome.exe
    PortableCommandAlias: chrome
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/141.0.7390.122-1.1/ungoogled-chromium_141.0.7390.122-1.1_windows_x86.zip
  InstallerSha256: DE502770D6C62E63BBBB0F202FD144191A0E532D1E70127B29226D14940A3B5A
  ArchiveBinariesDependOnPath: true
- Architecture: arm64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/141.0.7390.122-1.1/ungoogled-chromium_141.0.7390.122-1.1_installer_arm64.exe
  InstallerSha256: 344E687F3E14A30A7D30348E123E08CA02F6B7703441E83BE043FDB87687F8AF
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
- Architecture: arm64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/141.0.7390.122-1.1/ungoogled-chromium_141.0.7390.122-1.1_installer_arm64.exe
  InstallerSha256: 344E687F3E14A30A7D30348E123E08CA02F6B7703441E83BE043FDB87687F8AF
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
    Custom: --system-level
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ungoogled-chromium_141.0.7390.122-1.1_windows_arm64\chrome.exe
    PortableCommandAlias: chrome
  InstallerUrl: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/141.0.7390.122-1.1/ungoogled-chromium_141.0.7390.122-1.1_windows_arm64.zip
  InstallerSha256: 9E7BE7B1B1C90F68AA1F37238F5B5005AA4D2BCFA200B9D255A2A0EFEC99928B
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-10-25
