# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Amazon.AWSCLI
PackageVersion: 2.31.22
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- aws
ProductCode: '{2FE281DF-66F0-46CE-BCA1-38923414FE30}'
ReleaseDate: 2025-10-24
AppsAndFeaturesEntries:
- DisplayName: AWS Command Line Interface v2
  ProductCode: '{2FE281DF-66F0-46CE-BCA1-38923414FE30}'
  UpgradeCode: '{E1C1971C-384E-4D6D-8D02-F1AC48281CF8}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Amazon\AWSCLIV2'
Installers:
- Architecture: x64
  InstallerUrl: https://awscli.amazonaws.com/AWSCLIV2-2.31.22.msi
  InstallerSha256: 5B1D35B19B5D3EE5DD4AEA005AC624919810F52C9CE759EAC484ABEE85BB85D4
ManifestType: installer
ManifestVersion: 1.10.0
