# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: InterfaceFluidics.Autobench.Beta
PackageVersion: 0.95.1.0
Platform:
- Windows.Universal
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msix
PackageFamilyName: Autobench-Beta_adgv3mcaarp50
Installers:
- Architecture: neutral
  InstallerUrl: https://apps.interfacefluidics.com/autobench/beta/0.95.1.0/autobench-0.95.1.0.msix
  InstallerSha256: 9698A21FF5D1E6B52948E8C8D0C1411ABAFACFE56B27B0680776DD50CBDB3DE9
  SignatureSha256: 38FBE4FF5C43C77F274CC8AD2AF25B1D36E2E81FA038D697DB38EE9A0A03FB81
ManifestType: installer
ManifestVersion: 1.9.0
