# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: RareWares.FLAC
PackageVersion: 1.4.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: flac.exe
  PortableCommandAlias: flac
- RelativeFilePath: metaflac.exe
  PortableCommandAlias: metaflac
Installers:
- InstallerUrl: https://www.rarewares.org/files/lossless/flac-1.4.3-x64-20240525.zip
  Architecture: x64
  InstallerSha256: 0C41FF6A195D06060A92FEA3748F720C0A02ED1CA0673A97F55876059DB247E5
- InstallerUrl: https://www.rarewares.org/files/lossless/flac-1.4.3-x86-nonXP-20240525.zip
  Architecture: x86
  InstallerSha256: 616F11171E67929E15624893205DB8AF20464E53B68F9F5CDABBE5FE49D3F4DA
ManifestType: installer
ManifestVersion: 1.6.0
