# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: trzsz.tssh
PackageVersion: 0.1.23
PackageLocale: en-US
Publisher: trzsz
PublisherUrl: https://trzsz.github.io/ssh
PublisherSupportUrl: https://github.com/trzsz/trzsz-ssh/issues
Author: Lonny Wong
PackageName: tssh
PackageUrl: https://github.com/trzsz/trzsz-ssh
License: MIT License
LicenseUrl: https://github.com/trzsz/trzsz-ssh/blob/main/LICENSE
ShortDescription: Simple ssh client that supports trzsz, supports searching and selecting servers for batch login.
Tags:
- trzsz trz tsz rz sz ssh zmodem
ReleaseNotesUrl: https://github.com/trzsz/trzsz-ssh/releases/tag/v0.1.23
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/trzsz/trzsz-ssh/wiki
ManifestType: defaultLocale
ManifestVersion: 1.10.0
