# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: BellSoft.LibericaJRE.25.Full
PackageVersion: 25.0.1+11
InstallerLocale: en-US
InstallerType: wix
Scope: machine
ReleaseDate: 2025-10-20
Installers:
- Architecture: x64
  InstallerUrl: https://download.bell-sw.com/java/25.0.1+11/bellsoft-jre25.0.1+11-windows-amd64-full.msi
  InstallerSha256: B872F1E2AE52618491C14915BB5D53BAE0F011D9C1FDA26DF30783BA614A8716
  ProductCode: '{733291D4-60BD-41B2-B263-D12966022B46}'
  AppsAndFeaturesEntries:
  - DisplayName: Liberica JRE 25 Full (64-bit)
    DisplayVersion: 25.0.1.11
    ProductCode: '{733291D4-60BD-41B2-B263-D12966022B46}'
    UpgradeCode: '{DC724BF3-8FB8-4181-B81E-61E9EF13BA71}'
- Architecture: arm64
  InstallerUrl: https://download.bell-sw.com/java/25.0.1+11/bellsoft-jre25.0.1+11-windows-aarch64-full.msi
  InstallerSha256: 0CE8FDC4AC3FD96600069D9EA05C394A70C0CBA017448A42DF38B81350FF1679
  ProductCode: '{54551F20-6659-4BF1-AFDE-D835D96D0CAE}'
  AppsAndFeaturesEntries:
  - DisplayName: Liberica JRE 25 Full (AArch64)
    DisplayVersion: 25.0.1.11
    ProductCode: '{54551F20-6659-4BF1-AFDE-D835D96D0CAE}'
    UpgradeCode: '{C4653927-C2D4-4EBE-A549-8D3D52BBAB63}'
ManifestType: installer
ManifestVersion: 1.10.0
