# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Microsoft.Edge
PackageVersion: 141.0.3537.99
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- msedge
Protocols:
- http
- https
FileExtensions:
- crx
- htm
- html
- pdf
- url
AppsAndFeaturesEntries:
- UpgradeCode: '{883C2625-37F7-357F-A0F4-DFAF391B2B9C}'
Installers:
- Architecture: x86
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/44b088d1-0ae5-41c1-a15c-97f01fdfcda3/MicrosoftEdgeEnterpriseX86.msi
  InstallerSha256: DF237108E87BD851DCDFCE7549A98B2C5B37C55ADDB2D8952C67901A80BAB73C
  ProductCode: '{F1FDFE89-1256-3B3D-A48A-CD7EF61E6F33}'
- Architecture: x64
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/7c2821c1-1f64-440d-bd8b-a9f566748f12/MicrosoftEdgeEnterpriseX64.msi
  InstallerSha256: 37214525E8A573AD9A8E4E8EF3CD7B3452496A13FF4611471FE2CA62ED51CF6E
  ProductCode: '{BB68E114-48D5-3735-AB3C-C4D02FB91AE2}'
- Architecture: arm64
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/31705af4-c223-415d-9110-56acd078abdb/MicrosoftEdgeEnterpriseARM64.msi
  InstallerSha256: 26CD9F5FAB1E44D5D60C806E987EFC8CA30FA1324B5894399C6071BB8BD6E733
  ProductCode: '{3806A442-3108-3B1F-8548-2C891BD2190F}'
ManifestType: installer
ManifestVersion: 1.10.0
