# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Oracle.MySQLWorkbench
PackageVersion: 8.0.44
InstallerLocale: en-US
InstallerType: wix
Scope: machine
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: '{A30BD638-8BF3-4782-A2B5-1956738D9E4E}'
ReleaseDate: 2025-10-13
AppsAndFeaturesEntries:
- ProductCode: '{A30BD638-8BF3-4782-A2B5-1956738D9E4E}'
  UpgradeCode: '{84C668F4-A0C9-4585-A463-AADE0EFC9391}'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\.\MySQL\MySQL Workbench 8.0 CE\.'
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.mysql.com//Downloads/MySQLGUITools/mysql-workbench-community-8.0.44-winx64.msi
  InstallerSha256: A94535296037706856061C41FFDAD61C1BC917324FEFF7B95C12A6335C926B82
ManifestType: installer
ManifestVersion: 1.10.0
