# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Oracle.MySQLWorkbench
PackageVersion: 8.0.44
PackageLocale: en-US
Publisher: Oracle Corporation
PrivacyUrl: https://www.oracle.com/legal/privacy
PackageName: MySQL Workbench 8.0 CE
License: GNU General Public License version 2
ShortDescription: |
  Integrated tools environment for database design, modeling, development, administration, and migration.
ManifestType: defaultLocale
ManifestVersion: 1.10.0
