# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Box.Box
PackageVersion: 2.47.174
InstallerLocale: en-US
InstallerType: msi
Scope: machine
InstallerSwitches:
  InstallLocation: APPDIR="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- boxdrive
FileExtensions:
- boxcanvas
- boxnote
- gdoc
- gsheet
- gslide
- gslides
ProductCode: '{9B5B8D73-52DC-4CC9-B641-00F0437F8F25}'
ReleaseDate: 2025-10-01
AppsAndFeaturesEntries:
- ProductCode: '{9B5B8D73-52DC-4CC9-B641-00F0437F8F25}'
  UpgradeCode: '{46AF5B38-D258-487A-92BD-792911248CCD}'
InstallationMetadata:
  DefaultInstallLocation: APPDIR:.
Installers:
- Architecture: x64
  InstallerUrl: https://e3.boxcdn.net/desktop/releases/win/BoxDrive-2.47.174.msi
  InstallerSha256: 6A5E8A821B98876EAE1CAA9D9B8B7AEBC43B3315BA7BF652F2E7EF9CEB80121F
ManifestType: installer
ManifestVersion: 1.10.0
