# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.VisualStudio.Enterprise.Insiders
PackageVersion: 18.0.11121.172
InstallerSwitches:
  Silent: --quiet
  SilentWithProgress: --passive
  Upgrade: update
  Custom: --wait
ExpectedReturnCodes:
- InstallerReturnCode: 1001
  ReturnResponse: installInProgress
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 1618
  ReturnResponse: installInProgress
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 1003
  ReturnResponse: fileInUse
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 1641
  ReturnResponse: rebootInitiated
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 3010
  ReturnResponse: rebootRequiredToFinish
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5004
  ReturnResponse: cancelledByUser
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8001
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8002
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8003
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8004
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8005
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8007
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8008
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8009
  ReturnResponse: blockedByPolicy
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: -1073720687
  ReturnResponse: noNetwork
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: -2146233083
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 740
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5001
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5002
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5003
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5005
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5007
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 5008
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
- InstallerReturnCode: 8006
  ReturnResponse: custom
  ReturnResponseUrl: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/installation/issues-workarounds-visual-studio-setup
Commands:
- devenv
AppsAndFeaturesEntries:
- DisplayVersion: 18.0.0 Insiders [11121.172]
Installers:
- Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://download.visualstudio.microsoft.com/download/pr/39b7611e-81c3-43bd-8dd1-ac87a8be4188/3c0a9f6ce849cfefb43a50e6658f97b925ea853aeb97af9a3cb94917d54d3c85/vs_Enterprise.exe
  InstallerSha256: 3c0a9f6ce849cfefb43a50e6658f97b925ea853aeb97af9a3cb94917d54d3c85
ManifestType: installer
ManifestVersion: 1.9.0
