# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: TeamViewer.TeamViewer.Host
PackageVersion: 15.54.3
Platform:
- Windows.Desktop
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://dl.teamviewer.com/download/version_15x/TeamViewer_Host_Setup.exe
  InstallerSha256: 9FBE6E92981A92D85C76F950CBE899D01BECDD0ADC25DBA95AC07BBD47D32EB3
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://dl.teamviewer.com/download/version_15x/TeamViewer_Host_Setup_x64.exe
  InstallerSha256: 436F9601CEB9098D1E7C21F39C6DC7CE8EA7E79AAE01709110EEBBC3C618F53B
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: wix
  NestedInstallerFiles:
  - RelativeFilePath: Host\TeamViewer_Host.msi
  InstallerUrl: https://download.teamviewer.com/download/version_15x/TeamViewer_MSI32.zip
  InstallerSha256: A0F6FE60003497A620102F2DF3AD37ECA52E443498B0A012BB3A5032CEE10122
  ProductCode: '{38E9CBDD-0C8A-4A68-9DA0-F714E829084D}'
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: wix
  NestedInstallerFiles:
  - RelativeFilePath: Host\TeamViewer_Host.msi
  InstallerUrl: https://download.teamviewer.com/download/version_15x/TeamViewer_MSI64.zip
  InstallerSha256: 90228647E2BFA9587529CFAFB9ABD73E849363D1097309E8127128B602C44D95
  ProductCode: '{B16CCF79-2FC6-447F-9846-9BF1095B4105}'
ManifestType: installer
ManifestVersion: 1.6.0
